Update touch command

diff --git a/kubernetes/manifests/arm/values.yaml b/kubernetes/manifests/arm/values.yaml
--- a/kubernetes/manifests/arm/values.yaml
+++ b/kubernetes/manifests/arm/values.yaml
@@ -16,12 +16,8 @@ common:
           - /bin/sh
           - -c
           - |
-            if [ ! -f "/etc/container_environment.sh" ]; then
-              touch "/etc/container_environment.sh"
-            fi
-            if [ ! -f "/etc/container_environment.json" ]; then
-              touch "/etc/container_environment.json"
-            fi
+            touch "/etc/container_environment.sh" || { echo "Error creating /etc/container_environment.sh"; }
+            touch "/etc/container_environment.json" || { echo "Error creating /etc/container_environment.json"; }
             chown -R 1000:1000 /home/arm/media
             chown -R 1000:1000 /etc/arm/config
             chown -R 1000:1000 /etc/container_environment
